### ISSUE TITLE
TODO: python 3.4 rebuild 

### ISSUE THREAD

**Issue by felixonmars** [archlinuxcn/repo#12]
TODO:
- [ ] archlinuxcn/mysql-python3
- [x] archlinuxcn/python-cld2-hg
- [x] archlinuxcn/python-greenlet-git
- [x] archlinuxcn/python-http-parser-git
- [x] archlinuxcn/python-lupa
- [x] archlinuxcn/python-magic-git
- [x] archlinuxcn/python-memoryprofiler
- [x] archlinuxcn/python-motor
- [x] archlinuxcn/python-pygal-git
- [x] archlinuxcn/python-pyside
- [x] archlinuxcn/python-pyside-tools
- [x] archlinuxcn/python-redis-git
- [x] archlinuxcn/python-regex-hg
- [ ] archlinuxcn/python-romkan-git
- [x] archlinuxcn/python-svgwrite
- [x] archlinuxcn/shiboken
- [x] archlinuxcn/you-get-git

Packages should be updated once python 3.4 released to [extra]. (currently in [testing], and will be likely moved next week)

NOTE: Please check if the package works in python 3.4, like some PKGBUILD have the old python version "3.3" somewhere in build script. Also if the package were taken from AUR, corresponding changes should happen there too.
