### ISSUE TITLE
TODO: cleanup of old out-of-date packages

### ISSUE THREAD

**Issue by felixonmars** [archlinuxcn/repo#13]
Here's a TODO for packages that are out-of-date for more than 3 months, please either update them, or drop them, thanks!

I've also attached the date that one package becomes out-of-date
- [x] appmenu-gtk @Amesists ~Jun 16 2013
- [x] bbswitch-dkms @cuihaoleo ~Dec 6 2013
- [ ] cairo-ubuntu @cuihaoleo ~Aug 29 2013
- [ ] fontconfig-ubuntu @cuihaoleo ~Dec 12 2013
- [ ] freetype2-ubuntu @cuihaoleo ~Dec 13 2013
- [x] mozplugger @cuihaoleo ~Nov 25 2013
- [ ] zabbix-server-mysql @wych42 ~Oct 12 2013

Will add more once I have time to check further (please help as you can too :P)...
