### ISSUE TITLE
OpenSSL 3.0 rebuild

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#3014]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* [x] eternalterminal-client
* [x] eternalterminal-htm
* [x] eternalterminal-server
* [ ] mariadb-clients-git
* [ ] mariadb-libs-git
* [ ] vmware-workstation-macos
* [ ] netease-cloud-music-gtk4 (@BruceZhang1993)
* [ ] php-swoole (@BruceZhang1993)
* [x] proton-ge-custom-opt (@CoelacanthusHex)
* [ ] lib32-gst-plugins-bad (@DDoSolitary)
* [ ] lib32-neon (@DDoSolitary)
* [ ] lib32-srt (@DDoSolitary)
* [ ] libtins (@DDoSolitary)
* [ ] qv2ray-plugin-ssr-dev-git (@DuckSoft)
* [ ] qv2ray-plugin-trojan-dev-git (@DuckSoft)
* [ ] trojan-git (@DuckSoft)
* [ ] revda-git (@MarvelousBlack)
* [x] ciel (@OriginCode)
* [ ] firefox-pwa (@PeterCxy)
* [x] espanso (@Sasasu)
* [x] qbittorrent-enhanced-git (@Sasasu)
* [x] ddnet (@SilverRainZ)
* [x] srain (@SilverRainZ)
* [x] srain-git (@SilverRainZ)
* [x] wrk (@SilverRainZ)
* [x] aw-watcher-window-wayland-git (@Y7n05h)
* [x] paru-git (@Y7n05h)
* [x] rust-fleet-git (@Y7n05h)
* [ ] gcsf (@axionl)
* [ ] gcsf-git (@axionl)
* [ ] lemmy (@axionl)
* [ ] systemd-git (@axionl)
* [ ] tinc-pre (@cuihaoleo)
* [ ] yubico-piv-tool (@cuihaoleo)
* [ ] mailsync (@dctxmei)
* [ ] moonlight-qt (@dctxmei)
* [ ] spotify-tui (@dctxmei)
* [ ] trojan-dctxmei (@dctxmei)
* [ ] freshplayerplugin (@farseerfc)
* [ ] mbuffer (@farseerfc)
* [ ] meli-git (@farseerfc)
* [ ] srcml (@farseerfc)
* [ ] telegram-desktop-git (@farseerfc)
* [ ] vmware-workstation (@farseerfc)
* [ ] ydcv-rs-git (@farseerfc)
* [ ] zchunk (@farseerfc)
* [ ] listenbrainz-mpd (@frantic1048)
* [ ] plex-media-server (@frantic1048)
* [ ] alvr (@heavysink)
* [ ] citra-canary-git (@heavysink)
* [ ] citra-git (@heavysink)
* [ ] decaf-emu-git (@heavysink)
* [ ] genymotion (@heavysink)
* [ ] lib32-qt4 (@heavysink)
* [ ] mariadb-git (@heavysink)
* [ ] miktex (@heavysink)
* [ ] moonplayer (@heavysink)
* [ ] np2kai-git (@heavysink)
* [ ] python2 (@heavysink)
* [ ] qt4 (@heavysink)
* [ ] rstudio-desktop-git (@heavysink)
* [ ] supertuxkart-git (@heavysink)
* [ ] virtualbox-svn (@heavysink)
* [ ] vlc-git (@heavysink)
* [ ] xemu-git (@heavysink)
* [ ] yuzu-early-access (@heavysink)
* [ ] yuzu-git (@heavysink)
* [x] 3dslicer (@hubutui)
* [x] 3dslicer-bin (@hubutui)
* [x] 3dslicer-git (@hubutui)
* [x] 3dslicer-nightly-bin (@hubutui)
* [x] dcmtk (@hubutui)
* [x] gdcm (@hubutui)
* [ ] miniconda (@hubutui)
* [x] python-tokenizers (@hubutui)
* [x] collectd (@lilydjwg)
* [x] mosh-git (@lilydjwg)
* [x] pacman-lily (@lilydjwg)
* [x] sysdig-lily (@lilydjwg)
* [ ] megatools (@petronny)
* [ ] proftpd (@petronny)
* [x] uxplay-git (@sihuan)
* [ ] imgpatchtools-git (@simonsmh)
* [x] clash-verge (@sukanka)
* [x] apache-tools (@wfxr)
* [ ] 64gram-desktop (@wuyudi @dctxmei)
* [ ] anaconda (@xgdgsc)
* [ ] rstudio-desktop-bin (@xgdgsc)
* [x] input-leap-git (@yan12125): #3013
* [x] input-leap-headless-git (@yan12125): #3013
* [x] synergy-git (@yan12125): https://github.com/archlinuxcn/repo/commit/15d189ea6129af4c1226efd7db3118f4673712c1
* [x] unbound-python (@yan12125): #3013
* [ ] makemkv (@ykelvis)
* [ ] megasync (@ykelvis)
* [ ] ncspot-git (@ykelvis)
* [ ] netatalk (@ykelvis)
* [ ] rescrobbled-git (@ykelvis)
* [x] ccnet-server (@yuyichao)
* [x] eternalterminal (@yuyichao)
* [x] libgit2-julia (@yuyichao)
* [x] mtxclient (@yuyichao)
* [x] mtxclient-git (@yuyichao)
* [x] seafile-server (@yuyichao)
* [x] netease-music-tui (@zjuyk)

----

以上包链接到了 libssl.so.1.1 或者 libcrypto.so.1.1。请确认是否需要重新编译。

<summary>
<code>./who_depends_this_lib /data/repo/x86_64/archlinuxcn.files.tar.gz 'lib(?:ssl|crypto)\.so\.1\.1' --dep-pkgname openssl</code> 输出
<details>

```
3dslicer-5.0.3-4: opt/3dslicer/lib/Python/lib/python3.9/lib-dynload/_ssl.so (libcrypto.so.1.1)
3dslicer-bin-5.0.3-2: opt/3dslicer/lib/Slicer-5.0/qt-loadable-modules/vtkSlicerVolumesModuleLogicPython.so (libssl.so.1.1)
3dslicer-git-5.1.0.r28101.f9bd656dc6-1: opt/3dslicer/lib/Python/lib/python3.9/lib-dynload/_ssl.so (libcrypto.so.1.1)
3dslicer-nightly-bin-20221031.153359-1: opt/3dslicer/lib/Slicer-5.1/qt-loadable-modules/vtkSlicerVolumesModuleLogicPython.so (libssl.so.1.1)
64gram-desktop-1:1.0.50-1: usr/bin/64gram-desktop (libssl.so.1.1)
alvr-18.2.3-2: usr/lib/steamvr/alvr/bin/linux64/driver_alvr_server.so (libssl.so.1.1)
anaconda-2022.10-1: opt/anaconda/pkgs/wget-1.21.3-h0b77cf5_0/bin/wget (libcrypto.so.1.1)
apache-tools-2.4.54-1: usr/bin/ab (libssl.so.1.1)
aw-watcher-window-wayland-git-r27.1cd0555-2: usr/bin/aw-watcher-window-wayland (libssl.so.1.1)
ccnet-server-7.1.5-3: usr/bin/ccnet-server (libcrypto.so.1.1)
ciel-3.1.0-1: usr/bin/ciel (libssl.so.1.1)
citra-canary-git-1:2312.r0.g62507595f-2: usr/bin/citra-room (libssl.so.1.1)
citra-git-r9313.4d684174e-1: usr/bin/citra-room (libssl.so.1.1)
clash-verge-1.1.2-2: usr/bin/clash-verge (libssl.so.1.1)
collectd-5.12.0-9: usr/lib/collectd/write_stackdriver.so (libssl.so.1.1)
dcmtk-3.6.7-2: usr/lib/libdcmtls.so.17.3.6.7 (libssl.so.1.1)
ddnet-16.5-1: usr/bin/DDNet-Server (libcrypto.so.1.1)
decaf-emu-git-5216.e8c9af30-1: usr/bin/decaf-sdl (libcrypto.so.1.1)
espanso-0.7.3-1: usr/bin/espanso (libssl.so.1.1)
eternalterminal-6.2.1-4: usr/bin/htm (libssl.so.1.1)
eternalterminal-client-6.2.1-4: usr/bin/htm (libssl.so.1.1)
eternalterminal-htm-6.2.1-4: usr/bin/htmd (libssl.so.1.1)
eternalterminal-server-6.2.1-4: usr/bin/etterminal (libssl.so.1.1)
firefox-pwa-2.1.2-1: usr/bin/firefoxpwa (libssl.so.1.1)
freshplayerplugin-0.3.11-3: usr/lib/mozilla/plugins/libfreshwrapper-flashplayer.so (libcrypto.so.1.1)
gcsf-0.1.25-1: usr/bin/gcsf (libssl.so.1.1)
gcsf-git-r252.1260b66-1: usr/bin/gcsf (libssl.so.1.1)
gdcm-3.0.19-2: usr/lib/libgdcmCommon.so.3.0.19 (libcrypto.so.1.1)
genymotion-3.2.1-2: opt/genymotion/plugins/libgmplayerplugin.so (libcrypto.so.1.1)
imgpatchtools-git-0.3.r11.g30dcd07-2: usr/bin/imgdiff (libssl.so.1.1)
input-leap-git-2.4.0+299+g20423846-2: usr/bin/barrier (libcrypto.so.1.1)
input-leap-headless-git-2.4.0+299+g20423846-2: usr/bin/barriers (libssl.so.1.1)
lemmy-0.16.7-1: usr/bin/lemmy_server (libssl.so.1.1)
lib32-gst-plugins-bad-1.18.5-2: usr/lib32/gstreamer-1.0/libgstdtls.so (libcrypto.so.1.1)
lib32-neon-0.32.2-1: usr/lib32/libneon.so.27.5.2 (libssl.so.1.1)
lib32-qt4-4.8.7-15: usr/lib32/libQtNetwork.so.4.8.7 (libssl.so.1.1)
lib32-srt-1.4.4-1: usr/lib32/libsrt.so.1.4.4 (libcrypto.so.1.1)
libgit2-julia-1:1.5.0-1: usr/lib/libgit2.so.1.5.0 (libssl.so.1.1)
libtins-4.2-3: usr/lib/libtins.so.4.2 (libcrypto.so.1.1)
listenbrainz-mpd-2.0.0-1: usr/bin/listenbrainz-mpd (libssl.so.1.1)
mailsync-5.2.1-2: usr/bin/mailsync (libssl.so.1.1)
makemkv-1.17.2-1: usr/lib/libmmbd.so.0 (libcrypto.so.1.1)
mariadb-clients-git-10.9.3.r218.g4b87d3628ac-7: usr/bin/mariadb-test (libssl.so.1.1)
mariadb-git-10.9.3.r218.g4b87d3628ac-7: usr/bin/test-connect-t (libssl.so.1.1)
mariadb-libs-git-10.9.3.r218.g4b87d3628ac-7: usr/lib/mysql/plugin/sha256_password.so (libcrypto.so.1.1)
mbuffer-20220418-1: usr/bin/mbuffer (libcrypto.so.1.1)
megasync-4.6.8.0-2: usr/bin/megasync (libssl.so.1.1)
megatools-1.11.0+20220519-1: usr/bin/megatools (libcrypto.so.1.1)
meli-git-alpha.0.7.2.r62.g5fa4b62-1: usr/bin/meli (libssl.so.1.1)
miktex-22.10-1: opt/miktex/lib/libmiktex-core.so.4.16.0 (libcrypto.so.1.1)
miniconda-4.12.0-1: opt/miniconda/pkgs/python-3.9.12-h12debd9_0/lib/python3.9/lib-dynload/_ssl.cpython-39-x86_64-linux-gnu.so (libssl.so.1.1)
moonlight-qt-4.3.0-1: usr/bin/moonlight (libssl.so.1.1)
moonplayer-4.1-1: usr/bin/moonplayer-hlsdl (libcrypto.so.1.1)
mosh-git-1:1.4.0-1: usr/bin/mosh-server (libcrypto.so.1.1)
mtxclient-0.8.2-1: usr/lib/libmatrix_client.so.0.8.2 (libcrypto.so.1.1)
mtxclient-git-0.8.2.r33.g86bc6be-1: usr/lib/libmatrix_client.so.0.8.2 (libcrypto.so.1.1)
ncspot-git-0.11.2.r3.1dcebea-1: usr/bin/ncspot (libssl.so.1.1)
netatalk-3.1.13-3: usr/lib/netatalk/uams_randnum.so (libcrypto.so.1.1)
netease-cloud-music-gtk4-2.0.1-3: usr/bin/netease-cloud-music-gtk4 (libssl.so.1.1)
netease-music-tui-0.1.5-1: usr/bin/ncmt (libssl.so.1.1)
np2kai-git-1052.606fafa-1: usr/bin/xnp2kai (libcrypto.so.1.1)
pacman-lily-6.0.1-8: usr/lib/libalpm.so.13.0.1 (libcrypto.so.1.1)
paru-git-1.11.1.r64.g4a34ae9-1: usr/bin/paru (libssl.so.1.1)
php-swoole-4.8.8-1: usr/lib/php/modules/swoole.so (libssl.so.1.1)
plex-media-server-1.29.1.6316-1: usr/lib/plexmediaserver/lib/libssl.so.1.1 (libcrypto.so.1.1)
proftpd-2:1.3.7d-1: usr/bin/proftpd (libssl.so.1.1)
proton-ge-custom-opt-2:GE.Proton7.38-1: usr/share/steam/compatibilitytools.d/proton-ge-custom/files/lib64/gstreamer-1.0/libgstdtls.so (libcrypto.so.1.1)
python2-2.7.18-8: usr/lib/python2.7/lib-dynload/_ssl.so (libssl.so.1.1)
python-tokenizers-1:0.13.1-2: usr/lib/python3.10/site-packages/tokenizers/tokenizers.cpython-310-x86_64-linux-gnu.so (libssl.so.1.1)
qbittorrent-enhanced-git-4.4.3.12.r1.g4ffc2ccce-1: usr/bin/qbittorrent (libcrypto.so.1.1)
qt4-4.8.7-36: usr/lib/libQtNetwork.so.4.8.7 (libssl.so.1.1)
qv2ray-plugin-ssr-dev-git-20201214.r105.6f4f87e-1: usr/share/qv2ray/plugins/libQvPlugin-SSR.so (libcrypto.so.1.1)
qv2ray-plugin-trojan-dev-git-20210127.r69.1990d6f-5: usr/share/qv2ray/plugins/libQvPlugin-Trojan.so (libssl.so.1.1)
rescrobbled-git-0.6.1.r0.g8fc5476-1: usr/bin/rescrobbled (libssl.so.1.1)
revda-git-5.1.1.r0.ge16105f-1: usr/bin/revda (libssl.so.1.1)
rstudio-desktop-bin-2022.07.2.576-1: usr/lib/rstudio/bin/rstudio (libcrypto.so.1.1)
rstudio-desktop-git-39818.0995e6a6a2-1: usr/lib/rstudio/bin/rstudio (libcrypto.so.1.1)
rust-fleet-git-0.0.8.145.g17a8b0b-1: usr/bin/fleet (libssl.so.1.1)
seafile-server-8.0.1-5: usr/bin/seafserv-gc (libcrypto.so.1.1)
spotify-tui-0.25.0-2: usr/bin/spt (libssl.so.1.1)
srain-1:1.5.0-1: usr/bin/srain (libcrypto.so.1.1)
srain-git-1.5.0.1.g59a903a-1: usr/bin/srain (libcrypto.so.1.1)
srcml-1.0.0-2: usr/lib/libsrcml.so.1.0.0 (libcrypto.so.1.1)
supertuxkart-git-23098+18565-1: usr/bin/supertuxkart (libcrypto.so.1.1)
synergy-git-1:1.14.6.8.snapshot.r0.g9cedc57dc-1: usr/bin/synergys (libssl.so.1.1)
sysdig-lily-0.29.3-3: usr/bin/sysdig (libssl.so.1.1)
systemd-git-1:251.1007.g80f967311a-1: usr/lib/systemd/libsystemd-shared-251.so (libcrypto.so.1.1)
telegram-desktop-git-4.2.4.r10.g7b5781b84-1: usr/bin/telegram-desktop (libssl.so.1.1)
tinc-pre-1.1pre18-1: usr/bin/tincd (libcrypto.so.1.1)
trojan-dctxmei-1.16.0-1: usr/bin/trojan (libssl.so.1.1)
trojan-git-r466.3e7bb9a-7: usr/bin/trojan (libssl.so.1.1)
unbound-python-1.17.0-1: usr/lib/libunbound.so.8.1.20 (libssl.so.1.1)
uxplay-git-r867.5f72631-1: usr/bin/uxplay (libcrypto.so.1.1)
virtualbox-svn-95556-2: usr/lib/virtualbox/components/VBoxRT.so (libssl.so.1.1)
vlc-git-4.0.0.r21283.g4216987aec1-1: usr/lib/vlc/plugins/access/liblive555_plugin.so (libcrypto.so.1.1)
vmware-workstation-16.2.4-1: usr/lib/vmware-vix/Workstation-16.0.0/64bit/libvix.so (libssl.so.1.1)
vmware-workstation-macos-16.2.4-1: usr/lib/vmware-vix/Workstation-16.0.0/64bit/libvix.so (libssl.so.1.1)
wrk-4.2.0-1: usr/bin/wrk (libssl.so.1.1)
xemu-git-0.7.71.r0.g22db3304a4-1: usr/bin/xemu (libssl.so.1.1)
ydcv-rs-git-0.4.7.157-1: usr/bin/ydcv (libssl.so.1.1)
yubico-piv-tool-2.3.0-3: usr/lib/libykpiv.so.2.3.0 (libcrypto.so.1.1)
yuzu-early-access-3081-1: usr/bin/yuzu-room (libssl.so.1.1)
yuzu-git-r22409.6f6be615f3-1: usr/bin/yuzu-room (libssl.so.1.1)
zchunk-1.2.3-1: usr/lib/libzck.so.1.2.3 (libcrypto.so.1.1)
```
</details>
</summary>

**Comment by lilacbot** [comment]
Some maintainers (perhaps outside contributors) cannot be assigned: @petronny, @SilverRainZ, @sihuan, @zjuyk, @simonsmh, @sukanka, @yuyichao, @MarvelousBlack, @PeterCxy, @hubutui, @ykelvis, @xgdgsc, @wfxr, @lilydjwg, @OriginCode, @wuyudi, @Sasasu, @Y7n05h, @yan12125

**Comment by lilydjwg** [comment]
给 lilac 添加了 `libssl` 和 `libcrypto` 两个别名。

**Comment by sukanka** [comment]
求一位好心人帮我 rebuild `clash-verge`,我自己 bump 得提 pr

**Comment by SilverRainZ** [comment]
> 求一位好心人帮我 rebuild `clash-verge`,我自己 bump 得提 pr

我来吧。

**Comment by hubutui** [comment]
二进制包也受影响？

**Comment by lilydjwg** [comment]
@hubutui 这就要由打包者来确认了。自动化脚本可没有那么聪明。

**Comment by axionl** [comment]
systemd-git 系列已经弃置,不再维护

**Comment by hubutui** [comment]
miniconda 是二进制包啊，目前用起来没啥问题。先标记已经解决了。有别的问题再说吧。

**Comment by zjuyk** [comment]
netease-music-tui 我目前也不用了，弃置issue提了

**Comment by oldherl** [comment]
lib32-gst-plugins-bad-1.18.5-2: usr/lib32/gstreamer-1.0/libgstdtls.so (libcrypto.so.1.1)
lib32-qt4-4.8.7-15: usr/lib32/libQtNetwork.so.4.8.7 (libssl.so.1.1)
libtins-4.2-3: usr/lib/libtins.so.4.2 (libcrypto.so.1.1)
python2-2.7.18-12: usr/lib/python2.7/lib-dynload/_ssl.so (libssl.so.1.1)
qt4-4.8.7-36: usr/lib/libQtNetwork.so.4.8.7 (libssl.so.1.1)
rstudio-desktop-bin-2024.04.2.764-1: usr/lib/rstudio/resources/app/bin/rpostback (libssl.so.1.1)
srcml-1.0.0-2: usr/lib/libsrcml.so.1.0.0 (libcrypto.so.1.1)

**Comment by BruceZhang1993** [comment]
`php-swoole` 已弃置，不再重新打包
